export const FETCH_START = "FETCH_START";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_ERROR = "FETCH_ERROR";
export const SELECT_GRANT = "SELECT_GRANT";
export const CHANGE_TAB = "CHANGE_TAB";
//Filter Type
export const FILTER_SAVE = "FILTER_SAVE";
export const FILTER_GRANTS = "FILTER_GRANTS";
export const FILTER_GRANTS_RESET = "FILTER_GRANTS_RESET";

// Submit a Grant
export const ADD_GRANT_START = "ADD_GRANT_START";
export const ADD_GRANT_SUCCESS = "ADD_GRANT_SUCCESS";
export const ADD_GRANT_FAILURE = "ADD_GRANT_FAILURE";

export const CHECK_ADMIN = "CHECK_ADMIN";
export const SET_USER = "SET_USER";
// Submit a grant suggestion
export const SUBMIT_SUGGESTION_START = "SUBMIT_SUGGESTION_START";
export const SUBMIT_SUGGESTION_SUCCESS = "SUBMIT_SUGGESTION_SUCCESS";
export const SUBMIT_SUGGESTION_FAILURE = "SUBMIT_SUGGESTION_FAILURE";

// Delete a grant suggestion
export const DELETE_SUGGESTION_START = "DELETE_SUGGESTION_START"
export const DELETE_SUGGESTION_SUCCESS = "DELETE_SUGGESTION_SUCCESS"
export const DELETE_SUGGESTION_FAILURE = "DELETE_SUGGESTION_FAILURE"

// Update a Grant
export const UPDATE_GRANT_START = "UPDATE_GRANT_START";
export const UPDATE_GRANT_SUCCESS = "UPDATE_GRANT_SUCCESS";
export const UPDATE_GRANT_FAILURE = "UPDATE_GRANT_FAILURE";

//  Delete a Grant
export const DELETE_GRANT_START = "DELETE_GRANT_START";
export const DELETE_GRANT_SUCCESS = "DELETE_GRANT_SUCCESS";
export const DELETE_GRANT_FAILURE = "DELETE_GRANT_FAILURE";



