import {Error} from '../reduxTypes'

export enum SuggestionTypes {
    SUBMIT_SUGGESTION_START = 'SUBMIT_SUGGESTION_START',
    SUBMIT_SUGGESTION_SUCCESS = 'SUBMIT_SUGGESTION_SUCCESS',
    SUBMIT_SUGGESTION_FAILURE = 'SUBMIT_SUGGESTION_FAILURE',
    DELETE_SUGGESTION_START = 'DELETE_SUGGESTION_START',
    DELETE_SUGGESTION_SUCCESS = 'DELETE_SUGGESTION_SUCCESS',
    DELETE_SUGGESTION_FAILURE = ' DELETE_SUGGESTION_FAILURE',
    UPDATE_SUGGESTION_START = 'UPDATE_SUGGESTION_START',
    UPDATE_SUGGESTION_SUCCESS = 'UPDATE_SUGGESTION_SUCCESS',
    UPDATE_SUGGESTION_FAILURE = 'UPDATE_SUGGESTION_FAILURE'
}

export interface SuggestionState {

}
