name: build

on: [push, pull_request]

jobs:
  coverage:
    name: Test and publish test coverage to Code Climate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "12"
      - run: npm install
      - uses: paambaati/codeclimate-action@v2.4.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CodeClimateReporterId }}
          CI: true
        with:
          coverageCommand: npm run coverage
          debug: true
